//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmongUsCE_AnimationEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentItems {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentItems"]));
            }
            set {
                this["RecentItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color DefaultImageBGRefrence {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultImageBGRefrence"]));
            }
            set {
                this["DefaultImageBGRefrence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color DefaultImageBG {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultImageBG"]));
            }
            set {
                this["DefaultImageBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color DefaultFrameBorder {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultFrameBorder"]));
            }
            set {
                this["DefaultFrameBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color DefaultFrameBorderRefrence {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultFrameBorderRefrence"]));
            }
            set {
                this["DefaultFrameBorderRefrence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color DefaultFrameBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultFrameBackground"]));
            }
            set {
                this["DefaultFrameBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color DefaultFrameBackgroundRefrence {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultFrameBackgroundRefrence"]));
            }
            set {
                this["DefaultFrameBackgroundRefrence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color DefaultAlignmentLinesColor {
            get {
                return ((global::System.Windows.Media.Color)(this["DefaultAlignmentLinesColor"]));
            }
            set {
                this["DefaultAlignmentLinesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDarkMode {
            get {
                return ((bool)(this["UseDarkMode"]));
            }
            set {
                this["UseDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastRefrenceFolder {
            get {
                return ((string)(this["LastRefrenceFolder"]));
            }
            set {
                this["LastRefrenceFolder"] = value;
            }
        }
    }
}
